version: '3'

services:
  yohanestatus:
    build:
      context: .
      dockerfile: Dockerfile
    image: datenshicommunity/yohanestatus:1.0.0
    ports:
      - "3000:3000"
    environment:
      - DB_USER=db_user
      - DB_PASS=pass
      - DB_HOST=localhost
      - DB_PORT=3306
      - DB_NAME=db_name
      - RO_SERVER_ADDRESS=127.0.0.1
      - RO_SERVER_PORT=6969
      - MC_SERVER_ADDRESS=127.0.0.1
    restart: always
